In [4]:
import numpy as np
import sympy as sp

In [6]:
def criar_vetor_de_simbolos(tamanho):
    """
    Cria um vetor (lista) de símbolos SymPy com o tamanho especificado.

    Parameters:
    tamanho (int): O número de símbolos a serem criados.

    Returns:
    list: Lista contendo os símbolos criados.
    """
    # Cria os símbolos usando sp.symbols
    return sp.symbols(f'x1:{tamanho+1}')

In [5]:
sp.Matrix(np.array_split(criar_vetor_de_simbolos(4), 2))

Matrix([
[x1, x2],
[x3, x4]])

In [7]:
# Função para calcular o produto Kronecker considerando binário exclusivo
def kronecker_binary(vectors):
    result = np.array([1])  # Inicia com o elemento neutro da multiplicação
    for v in vectors:
        result = np.kron(result, v)
    return result

In [8]:
kronecker_binary([[1,0],[0,1]])

array([0, 1, 0, 0])

In [ ]:
bits = 3
variaveis = sp.Matrix(kronecker_binary(np.array_split(criar_vetor_de_simbolos(bits*2), bits)))
variaveis

Matrix([
[x1*x3*x5],
[x1*x3*x6],
[x1*x4*x5],
[x1*x4*x6],
[x2*x3*x5],
[x2*x3*x6],
[x2*x4*x5],
[x2*x4*x6]])

In [11]:
# Iterando pelo vetor com o índice e o valor
for linha, elemento in enumerate(variaveis):
    print(f"Linha {linha}: {elemento}")

Linha 0: x1*x3*x5
Linha 1: x1*x3*x6
Linha 2: x1*x4*x5
Linha 3: x1*x4*x6
Linha 4: x2*x3*x5
Linha 5: x2*x3*x6
Linha 6: x2*x4*x5
Linha 7: x2*x4*x6


In [12]:
def decimal_para_binario_vetor(numero_decimal, tamanho_bits=8):
    """
    Converte um número decimal para um vetor binário usando produtos de Kronecker.

    Args:
        numero_decimal (int): Número decimal a ser convertido.
        tamanho_bits (int, opcional): Número de bits para representar o número binário. Padrão é 8.

    Returns:
        np.ndarray: Vetor resultante da conversão.
    
    Raises:
        ValueError: Se o número decimal for negativo ou se o tamanho de bits for insuficiente.
    """
    # Mapeamento dos caracteres binários para os vetores desejados
    mapeamento = {'0': [1, 0], '1': [0, 1]}

    # Verifica se o número é um inteiro não negativo
    if not isinstance(numero_decimal, int):
        raise TypeError("O número decimal deve ser um inteiro.")
    if numero_decimal < 0:
        raise ValueError("A função não suporta números decimais negativos.")

    # Converter o número decimal para binário e remover o prefixo '0b'
    numero_binario = bin(numero_decimal)[2:]

    # Verifica se o número binário cabe no tamanho de bits desejado
    if len(numero_binario) > tamanho_bits:
        raise ValueError(f"O número binário '{numero_binario}' excede o tamanho de bits especificado ({tamanho_bits} bits).")

    # Adiciona zeros à esquerda para completar o tamanho de bits desejado
    numero_binario = numero_binario.zfill(tamanho_bits)

    # Inicializa o vetor com 1 para o produto de Kronecker
    vetor = np.array([1])
    
    # Aplica o produto de Kronecker para cada dígito binário
    for digito in numero_binario:
        vetor = np.kron(vetor, mapeamento[digito])

    return vetor

In [13]:
saida_tabela = [
	[0],
	[0],
	[0],
	[0],
	[0],
	[0],
	[0],
	[1],
]

vetores_binarios = []

for comb in saida_tabela:
	vetor = kronecker_binary(np.array([decimal_para_binario_vetor(bit, 1) for bit in comb]))
	vetores_binarios.append(vetor)

vetores_binarios = np.array(vetores_binarios).T
sp.Matrix(vetores_binarios)

Matrix([
[1, 1, 1, 1, 1, 1, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 1]])

In [14]:
regra = sp.Matrix(np.dot(vetores_binarios, variaveis)) # expressões simbólicas
regra

Matrix([
[x1*x3*x5 + x1*x3*x6 + x1*x4*x5 + x1*x4*x6 + x2*x3*x5 + x2*x3*x6 + x2*x4*x5],
[                                                                  x2*x4*x6]])

In [ ]:
# Iterando pelo vetor com o índice e o valor
for linha, elemento in enumerate(regra):
    print(f"Linha {linha}: {elemento}")

Linha 0: 0
Linha 1: 0
Linha 2: 0
Linha 3: 0
Linha 4: 0
Linha 5: 0
Linha 6: x1*x3*x5*x8
Linha 7: x1*x4*x6*x8
Linha 8: 0
Linha 9: 0
Linha 10: 0
Linha 11: 0
Linha 12: 0
Linha 13: 0
Linha 14: 0
Linha 15: 0
Linha 16: 0
Linha 17: 0
Linha 18: 0
Linha 19: 0
Linha 20: 0
Linha 21: 0
Linha 22: 0
Linha 23: 0
Linha 24: 0
Linha 25: 0
Linha 26: 0
Linha 27: 0
Linha 28: 0
Linha 29: 0
Linha 30: 0
Linha 31: 0
Linha 32: 0
Linha 33: 0
Linha 34: 0
Linha 35: 0
Linha 36: 0
Linha 37: 0
Linha 38: 0
Linha 39: 0
Linha 40: 0
Linha 41: 0
Linha 42: 0
Linha 43: 0
Linha 44: 0
Linha 45: 0
Linha 46: 0
Linha 47: 0
Linha 48: 0
Linha 49: 0
Linha 50: 0
Linha 51: 0
Linha 52: 0
Linha 53: 0
Linha 54: 0
Linha 55: 0
Linha 56: 0
Linha 57: x2*x4*x5*x7
Linha 58: 0
Linha 59: 0
Linha 60: 0
Linha 61: 0
Linha 62: 0
Linha 63: x1*x3*x5*x7
Linha 64: 0
Linha 65: 0
Linha 66: 0
Linha 67: 0
Linha 68: 0
Linha 69: 0
Linha 70: 0
Linha 71: 0
Linha 72: 0
Linha 73: 0
Linha 74: 0
Linha 75: 0
Linha 76: 0
Linha 77: 0
Linha 78: 0
Linha 79: x1*x3*x6*x8


In [ ]:
lista = regra.tolist()[0]
list(set([x for x in lista if lista.count(x) > 1]))

[]

In [ ]:
np.dot(vetores_binarios, decimal_para_binario_vetor(2, 4))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sympy.utilities.lambdify import lambdastr

#  Lista para armazenar as funções
funcoes = []

# Variáveis que as funções irão receber
variaveis = criar_vetor_de_simbolos(bits*2)

# Iterar sobre cada elemento do vetor simbólico e criar uma função
for expr in regra:
    func = sp.lambdify(variaveis, expr)
    funcoes.append(func)


In [ ]:
from sympy.utilities.lambdify import lambdastr

# Variáveis que as funções irão receber
variaveis = criar_vetor_de_simbolos(bits*2)

for expr in regra:
    print(lambdastr(variaveis, expr))

lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (x1*x3*x5*x8)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (x1*x4*x6*x8)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x

In [ ]:
import itertools

# Usando produto cartesiano
combinacoes = list(itertools.product([0, 1], repeat=4))

for comb in combinacoes:
	# Converte cada bit da combinação para um vetor binário e achata em uma única dimensão
	valores = np.array([decimal_para_binario_vetor(bit, 1) for bit in comb]).flatten()
	print(valores,[f(*valores) for f in funcoes])

[1 0 1 0 1 0 1 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 1] [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1 0 1 0 0 1 1 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0