In [23]:
import numpy as np
import sympy as sp

In [24]:
def criar_vetor_de_simbolos(tamanho):
    """
    Cria um vetor (lista) de símbolos SymPy com o tamanho especificado.

    Parameters:
    tamanho (int): O número de símbolos a serem criados.

    Returns:
    list: Lista contendo os símbolos criados.
    """
    # Cria os símbolos usando sp.symbols
    return sp.symbols(f'x1:{tamanho+1}')

In [25]:
sp.Matrix(np.array_split(criar_vetor_de_simbolos(4), 2))

Matrix([
[x1, x2],
[x3, x4]])

In [26]:
# Função para calcular o produto Kronecker considerando binário exclusivo
def kronecker_binary(vectors):
    result = np.array([1])  # Inicia com o elemento neutro da multiplicação
    for v in vectors:
        result = np.kron(result, v)
    return result

In [27]:
kronecker_binary([[1,0],[0,1]])

array([0, 1, 0, 0])

In [28]:
bits = 2
variaveis = sp.Matrix(kronecker_binary(np.array_split(criar_vetor_de_simbolos(bits*2), bits)))
variaveis

Matrix([
[x1*x3],
[x1*x4],
[x2*x3],
[x2*x4]])

In [38]:
bits = 4
variaveis = sp.Matrix(kronecker_binary(np.array_split(criar_vetor_de_simbolos(bits*2), bits)))
variaveis

Matrix([
[x1*x3*x5*x7],
[x1*x3*x5*x8],
[x1*x3*x6*x7],
[x1*x3*x6*x8],
[x1*x4*x5*x7],
[x1*x4*x5*x8],
[x1*x4*x6*x7],
[x1*x4*x6*x8],
[x2*x3*x5*x7],
[x2*x3*x5*x8],
[x2*x3*x6*x7],
[x2*x3*x6*x8],
[x2*x4*x5*x7],
[x2*x4*x5*x8],
[x2*x4*x6*x7],
[x2*x4*x6*x8]])

In [30]:
# Iterando pelo vetor com o índice e o valor
for linha, elemento in enumerate(variaveis):
    print(f"Linha {linha}: {elemento}")

Linha 0: x1*x11*x13*x3*x5*x7*x9
Linha 1: x1*x11*x14*x3*x5*x7*x9
Linha 2: x1*x12*x13*x3*x5*x7*x9
Linha 3: x1*x12*x14*x3*x5*x7*x9
Linha 4: x1*x10*x11*x13*x3*x5*x7
Linha 5: x1*x10*x11*x14*x3*x5*x7
Linha 6: x1*x10*x12*x13*x3*x5*x7
Linha 7: x1*x10*x12*x14*x3*x5*x7
Linha 8: x1*x11*x13*x3*x5*x8*x9
Linha 9: x1*x11*x14*x3*x5*x8*x9
Linha 10: x1*x12*x13*x3*x5*x8*x9
Linha 11: x1*x12*x14*x3*x5*x8*x9
Linha 12: x1*x10*x11*x13*x3*x5*x8
Linha 13: x1*x10*x11*x14*x3*x5*x8
Linha 14: x1*x10*x12*x13*x3*x5*x8
Linha 15: x1*x10*x12*x14*x3*x5*x8
Linha 16: x1*x11*x13*x3*x6*x7*x9
Linha 17: x1*x11*x14*x3*x6*x7*x9
Linha 18: x1*x12*x13*x3*x6*x7*x9
Linha 19: x1*x12*x14*x3*x6*x7*x9
Linha 20: x1*x10*x11*x13*x3*x6*x7
Linha 21: x1*x10*x11*x14*x3*x6*x7
Linha 22: x1*x10*x12*x13*x3*x6*x7
Linha 23: x1*x10*x12*x14*x3*x6*x7
Linha 24: x1*x11*x13*x3*x6*x8*x9
Linha 25: x1*x11*x14*x3*x6*x8*x9
Linha 26: x1*x12*x13*x3*x6*x8*x9
Linha 27: x1*x12*x14*x3*x6*x8*x9
Linha 28: x1*x10*x11*x13*x3*x6*x8
Linha 29: x1*x10*x11*x14*x3*x6*x8
Linha 

In [31]:
def decimal_para_binario_vetor(numero_decimal, tamanho_bits=8):
    """
    Converte um número decimal para um vetor binário usando produtos de Kronecker.

    Args:
        numero_decimal (int): Número decimal a ser convertido.
        tamanho_bits (int, opcional): Número de bits para representar o número binário. Padrão é 8.

    Returns:
        np.ndarray: Vetor resultante da conversão.
    
    Raises:
        ValueError: Se o número decimal for negativo ou se o tamanho de bits for insuficiente.
    """
    # Mapeamento dos caracteres binários para os vetores desejados
    mapeamento = {'0': [1, 0], '1': [0, 1]}

    # Verifica se o número é um inteiro não negativo
    if not isinstance(numero_decimal, int):
        raise TypeError("O número decimal deve ser um inteiro.")
    if numero_decimal < 0:
        raise ValueError("A função não suporta números decimais negativos.")

    # Converter o número decimal para binário e remover o prefixo '0b'
    numero_binario = bin(numero_decimal)[2:]

    # Verifica se o número binário cabe no tamanho de bits desejado
    if len(numero_binario) > tamanho_bits:
        raise ValueError(f"O número binário '{numero_binario}' excede o tamanho de bits especificado ({tamanho_bits} bits).")

    # Adiciona zeros à esquerda para completar o tamanho de bits desejado
    numero_binario = numero_binario.zfill(tamanho_bits)

    # Inicializa o vetor com 1 para o produto de Kronecker
    vetor = np.array([1])
    
    # Aplica o produto de Kronecker para cada dígito binário
    for digito in numero_binario:
        vetor = np.kron(vetor, mapeamento[digito])

    return vetor

In [61]:
saida_tabela = [
    [0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 0],
    [1, 0, 1, 1, 0, 1, 1],
    [1, 0, 0, 1, 1, 1, 1],
    [1, 1, 0, 0, 0, 1, 1],
    [1, 1, 0, 1, 1, 0, 1],
    [1, 1, 1, 1, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 0, 1, 1, 1, 1],
    [1, 1, 1, 0, 1, 1, 1],
    [1, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 1, 1, 1, 0],
    [1, 1, 1, 1, 0, 0, 1],
    [1, 1, 1, 0, 0, 0, 1]
]

#saida_tabela = [linha[::-1] for linha in saida_tabela]

vetores_binarios = []

for comb in saida_tabela:
	vetor = kronecker_binary(np.array([decimal_para_binario_vetor(bit, 1) for bit in comb]))
	vetores_binarios.append(vetor)

vetores_binarios = np.array(vetores_binarios).T
sp.Matrix(vetores_binarios)

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [62]:
# Lista para armazenar os índices de cada linha
resultado = []

# Percorre cada linha da matriz
for linha in vetores_binarios:
    indices = [i for i, val in enumerate(linha) if val == 1]
    resultado.append(indices if indices else [None])
    
resultado

[[None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [1],
 [7],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [12],
 [None],
 [None],
 [None],
 [None],
 [None],
 [0],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [3],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [2],
 [None],
 [None],
 [13],
 [None],
 [None],
 [None],
 [None],
 [4],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [5],
 [None],
 [9],
 [None],
 [15],
 [No

In [63]:
regra = sp.Matrix(np.dot(vetores_binarios, variaveis)) # expressões simbólicas
regra

Matrix([
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[x1*x3*x5*x8],
[x1*x4*x6*x8],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[          0],
[x2*x4*x5*x7],
[          0],
[          0],
[          0],
[          0],
[          0],
[x1*x3*x5*x7],
[          0],
[          0],
[

In [70]:
# Iterando pelo vetor com o índice e o valor
for linha, elemento in enumerate(regra):
    print(f"Linha {linha}: {elemento}")

Linha 0: 0
Linha 1: 0
Linha 2: 0
Linha 3: 0
Linha 4: 0
Linha 5: 0
Linha 6: x1*x3*x5*x8
Linha 7: x1*x4*x6*x8
Linha 8: 0
Linha 9: 0
Linha 10: 0
Linha 11: 0
Linha 12: 0
Linha 13: 0
Linha 14: 0
Linha 15: 0
Linha 16: 0
Linha 17: 0
Linha 18: 0
Linha 19: 0
Linha 20: 0
Linha 21: 0
Linha 22: 0
Linha 23: 0
Linha 24: 0
Linha 25: 0
Linha 26: 0
Linha 27: 0
Linha 28: 0
Linha 29: 0
Linha 30: 0
Linha 31: 0
Linha 32: 0
Linha 33: 0
Linha 34: 0
Linha 35: 0
Linha 36: 0
Linha 37: 0
Linha 38: 0
Linha 39: 0
Linha 40: 0
Linha 41: 0
Linha 42: 0
Linha 43: 0
Linha 44: 0
Linha 45: 0
Linha 46: 0
Linha 47: 0
Linha 48: 0
Linha 49: 0
Linha 50: 0
Linha 51: 0
Linha 52: 0
Linha 53: 0
Linha 54: 0
Linha 55: 0
Linha 56: 0
Linha 57: x2*x4*x5*x7
Linha 58: 0
Linha 59: 0
Linha 60: 0
Linha 61: 0
Linha 62: 0
Linha 63: x1*x3*x5*x7
Linha 64: 0
Linha 65: 0
Linha 66: 0
Linha 67: 0
Linha 68: 0
Linha 69: 0
Linha 70: 0
Linha 71: 0
Linha 72: 0
Linha 73: 0
Linha 74: 0
Linha 75: 0
Linha 76: 0
Linha 77: 0
Linha 78: 0
Linha 79: x1*x3*x6*x8


In [65]:
lista = regra.tolist()[0]
list(set([x for x in lista if lista.count(x) > 1]))

[]

In [68]:
#Sumulando saidas
teste = np.dot(vetores_binarios, decimal_para_binario_vetor(0, 4))
teste

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
[i for i, val in enumerate(teste) if val == 1]

[63]

In [71]:
# Lista para armazenar os índices de cada linha
resultado = []

# Percorre cada linha da matriz
for linha in vetores_binarios:
    indices = [i for i, val in enumerate(linha) if val == 1]
    resultado.append(indices if indices else [None])
    
resultado

[[None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [1],
 [7],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [12],
 [None],
 [None],
 [None],
 [None],
 [None],
 [0],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [3],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [2],
 [None],
 [None],
 [13],
 [None],
 [None],
 [None],
 [None],
 [4],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [None],
 [5],
 [None],
 [9],
 [None],
 [15],
 [No

In [ ]:
from sympy.utilities.lambdify import lambdastr

#  Lista para armazenar as funções
funcoes = []

# Variáveis que as funções irão receber
variaveis = criar_vetor_de_simbolos(bits*2)

# Iterar sobre cada elemento do vetor simbólico e criar uma função
for expr in regra:
    func = sp.lambdify(variaveis, expr)
    funcoes.append(func)


In [ ]:
from sympy.utilities.lambdify import lambdastr

# Variáveis que as funções irão receber
variaveis = criar_vetor_de_simbolos(bits*2)

for expr in regra:
    print(lambdastr(variaveis, expr))

lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (x1*x3*x5*x8)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (x1*x4*x6*x8)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x1,x2,x3,x4,x5,x6,x7,x8: (0)
lambda x

In [ ]:
import itertools

# Usando produto cartesiano
combinacoes = list(itertools.product([0, 1], repeat=4))

for comb in combinacoes:
	# Converte cada bit da combinação para um vetor binário e achata em uma única dimensão
	valores = np.array([decimal_para_binario_vetor(bit, 1) for bit in comb]).flatten()
	print(valores,[f(*valores) for f in funcoes])

[1 0 1 0 1 0 1 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1 0 1 0 1 0 0 1] [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1 0 1 0 0 1 1 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
list(itertools.product([0, 1], repeat=7))

[(0, 0, 0, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 1),
 (0, 0, 0, 0, 0, 1, 0),
 (0, 0, 0, 0, 0, 1, 1),
 (0, 0, 0, 0, 1, 0, 0),
 (0, 0, 0, 0, 1, 0, 1),
 (0, 0, 0, 0, 1, 1, 0),
 (0, 0, 0, 0, 1, 1, 1),
 (0, 0, 0, 1, 0, 0, 0),
 (0, 0, 0, 1, 0, 0, 1),
 (0, 0, 0, 1, 0, 1, 0),
 (0, 0, 0, 1, 0, 1, 1),
 (0, 0, 0, 1, 1, 0, 0),
 (0, 0, 0, 1, 1, 0, 1),
 (0, 0, 0, 1, 1, 1, 0),
 (0, 0, 0, 1, 1, 1, 1),
 (0, 0, 1, 0, 0, 0, 0),
 (0, 0, 1, 0, 0, 0, 1),
 (0, 0, 1, 0, 0, 1, 0),
 (0, 0, 1, 0, 0, 1, 1),
 (0, 0, 1, 0, 1, 0, 0),
 (0, 0, 1, 0, 1, 0, 1),
 (0, 0, 1, 0, 1, 1, 0),
 (0, 0, 1, 0, 1, 1, 1),
 (0, 0, 1, 1, 0, 0, 0),
 (0, 0, 1, 1, 0, 0, 1),
 (0, 0, 1, 1, 0, 1, 0),
 (0, 0, 1, 1, 0, 1, 1),
 (0, 0, 1, 1, 1, 0, 0),
 (0, 0, 1, 1, 1, 0, 1),
 (0, 0, 1, 1, 1, 1, 0),
 (0, 0, 1, 1, 1, 1, 1),
 (0, 1, 0, 0, 0, 0, 0),
 (0, 1, 0, 0, 0, 0, 1),
 (0, 1, 0, 0, 0, 1, 0),
 (0, 1, 0, 0, 0, 1, 1),
 (0, 1, 0, 0, 1, 0, 0),
 (0, 1, 0, 0, 1, 0, 1),
 (0, 1, 0, 0, 1, 1, 0),
 (0, 1, 0, 0, 1, 1, 1),
 (0, 1, 0, 1, 0, 0, 0),
 (0, 1, 0, 1, 0,

In [ ]:
"\overline{ab}cd+\overline{ab}c\overline{d}+ab\overline{c}d+\overline{a}b\overline{cd}+\overline{a}b\overline{c}d+a\overline{b}\overline{c}d+abcd+a\overline{b}c\overline{d}+abc\overline{d}+a\overline{b}cd+\overline{a}bc\overline{d}+a\overline{bcd}"

"https://www.boolean-algebra.com/?q=YWJ7Y2R9K3thYmNkfSt7YWJ9Y3tkfSthYntjfWQrYWJjZCthe2J9Y3tkfSthYmN7ZH0rYXtifWNkK3thfWJje2R9K2F7Yn17Y2R9"

"https://www.boolean-algebra.com/?q=YWJ7Y2R9K3thYmNkfSt7YWJ9Y2Qre2FifWN7ZH0rYWJ7Y31kK3thfWJ7Y31kK2F7Yn17Y31kK2FiY3tkfSthe2J9Y2Qre2F9YmN7ZH0rYXtifXtjZH0="

"https://www.boolean-algebra.com/?q=e2FifXtjfWQre2F9YmNkK3thYmNkfSt7YWJ9Y2QrYWJ7Y31kK3thfWJ7Y31kK2F7Yn17Y31kK2F7Yn1je2R9K2F7Yn1jZCt7YX1iY3tkfSthe2J9e2NkfQ=="

'https://www.boolean-algebra.com/?q=e2FifXtjfWQre2F9YmNkK3thYmNkfSt7YWJ9Y2QrYWJ7Y31kK3thfWJ7Y31kK2F7Yn17Y31kK2F7Yn1je2R9K2F7Yn1jZCt7YX1iY3tkfSthe2J9e2NkfQ=='